version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services: 
  
  dump1090exporter:
    container_name: dump1090exporter
    image: clawsicus/dump1090exporter:latest
    ports:
      - "9105:9105"
    restart: always
    stop_signal: SIGINT
    command: [
      "--resource-path=http://${HOST_IP:?IP_ADDRESS_UNSET_ERROR}:7070",
      "--debug"]

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.17.1
    depends_on:
      - dump1090exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana-arm32v7-linux:6.7.2
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - ${GRAFANA_PORT}:${GRAFANA_PORT}
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${DISABLE_LOGIN}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_DEFAULT_THEME=${GRAFANA_THEME}
      - GF_SERVER_GRAFANA_PORT=${GRAFANA_PORT}
